[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
access_control = "GQp4fJwxmLF7vL7uJ4jpS3uRz96qrb7MfoLKMnJoeE3Z"
data_feed = "7dTNTpTqbHCLxc1FtpCRAq5d4u1Y6WVqrAc1znVGQDxV"
midas_vaults = "6eFgYZCZZFTe61T4YxWsiHHAunCLTh9V7TAjj8DxuZwm"
token_authority = "6XqSwGFEuadyqXC9vBLYGJhvQsEVjPdCrtvN6inAb4z3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/midas_id.json"

[scripts]
script = "yarn run ts-node"

test = "RUST_LOG= yarn jest --maxWorkers=1 --testTimeout=1000000"
test-cargo = "cargo test-sbf"
test-ac = "yarn jest --maxWorkers=1 --testTimeout=1000000 test/ac.test.ts"
test-common = "yarn jest --maxWorkers=1 --testTimeout=1000000 test/common-vault.test.ts"
test-feed = "yarn jest --maxWorkers=1 --testTimeout=1000000 test/data-feed.test.ts"
test-minter = "yarn jest --maxWorkers=1 --testTimeout=1000000 test/minter-vault.test.ts"
test-redeemer = "yarn jest --maxWorkers=1 --testTimeout=1000000 test/redeemer-vault.test.ts"
test-auth = "yarn jest --maxWorkers=1 --testTimeout=1000000 test/token-authority.test.ts"
test-tokens = "yarn jest --maxWorkers=1 --testTimeout=1000000 test/mtokens.test.ts"
