[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
access_control = "7fmev1BQVc9LEXsMDoJs63muHR1B2uSAw1963zfVrpJP"
data_feed = "6vrYAbfttohJKguPRzspHUW6fn61KDyjzog3q8YRG6yq"
midas_vaults = "DHfwFSG3JQ2qdX1Ub2QPuDsk9FMQUwyXyZqAs4gGeLnQ"
token_authority = "GYmnAy5UiKMYuuwJubKKC5WLnWSW3qLo4JFqX4rBqHKE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/midas_id.json"

[scripts]
script = "tsx"
test = "RUST_LOG= yarn vitest run"
test-ac = "yarn vitest run test/ac.test.ts"
test-auth = "yarn vitest run test/token-authority.test.ts"
test-cargo = "cargo test-sbf"
test-common = "yarn vitest run test/common-vault.test.ts"
test-feed = "yarn vitest run test/data-feed.test.ts"
test-minter = "yarn vitest run test/minter-vault.test.ts"
test-redeemer = "yarn vitest run test/redeemer-vault.test.ts"
test-tokens = "yarn vitest run test/mtokens.test.ts"
