export enum MTokenNameEnum {
  mTBILL = "mTBILL",
  // mBASIS = 'mBASIS',
  // mBTC = 'mBTC',
  // mEDGE = 'mEDGE',
  // mRE7 = 'mRE7',
  // mRE7SOL = 'mRE7SOL',
  // mMEV = 'mMEV',
  // mSL = 'mSL',
  // mFONE = 'mFONE',
  // mHYPER = 'mHYPER',
  // mAPOLLO = 'mAPOLLO',
  // hbUSDT = 'hbUSDT',
  // hbXAUt = 'hbXAUt',
  // TACmBTC = 'TACmBTC',
  // TACmEDGE = 'TACmEDGE',
  // TACmMEV = 'TACmMEV',
  // mLIQUIDITY = 'mLIQUIDITY',
  // hypeETH = 'hypeETH',
  // hypeBTC = 'hypeBTC',
  // hypeUSD = 'hypeUSD',
  // tETH = 'tETH',
  // tUSDe = 'tUSDe',
  // tBTC = 'tBTC',
  // mevBTC = 'mevBTC',
  // lstHYPE = 'lstHYPE',
  // liquidHYPE = 'liquidHYPE',
  // hbUSDC = 'hbUSDC',
  // mFARM = 'mFARM',
}

export type MTokenName = keyof typeof MTokenNameEnum;

export enum PaymentTokenNameEnum {
  usdc = "usdc",
  usdt = "usdt",
  dai = "dai",
  m = "m",
  wbtc = "wbtc",
  pusd = "pusd",
  wrbtc = "wrbtc",
  usds = "usds",
  usde = "usde",
  usr = "usr",
  stone = "stone",
  weth = "weth",
  cmeth = "cmeth",
  weeth = "weeth",
  susde = "susde",
  rseth = "rseth",
  rsweth = "rsweth",
  sweth = "sweth",
  wsteth = "wsteth",
  lbtc = "lbtc",
  solvbtc = "solvbtc",
  cbbtc = "cbbtc",
  sbtc = "sbtc",
  enzobtc = "enzobtc",
  ebtc = "ebtc",
  swbtc = "swbtc",
  pumpbtc = "pumpbtc",
  xaut0 = "xaut0",
  usol = "usol",
  jitosol = "jitosol",
  usdhl = "usdhl",
  tbtc = "tbtc",
  wsthype = "wsthype",
  khype = "khype",
  whype = "whype",
}

export type PaymentTokenName = keyof typeof PaymentTokenNameEnum;
