name: Static Checks

on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v6.3.0
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Setup safe-chain
        run: |
          npm i -g @aikidosec/safe-chain
          safe-chain setup-ci
      - name: Install dependencies
        run: yarn

      # TODO: add lint, build, format checks
